// Interface automatically generated by schemas-to-ts

import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export enum Icon {
  Home = 'Home',
  WoRterbuch = 'Wörterbuch',
  Wortgeschichten = 'Wortgeschichten',
  Literatur = 'Literatur',
  UBerUns = 'Über uns',
  Projekte = 'Projekte',
  Kontakt = 'Kontakt',
  Englisch = 'Englisch',}

export interface Menu {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title: string;
    icon?: Icon;
    sub_menus: { data: Menu[] };
    parent_menu?: { data: Menu };
    link: string;
  };
}
export interface Menu_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  icon?: Icon;
  sub_menus: Menu_Plain[];
  parent_menu?: Menu_Plain;
  link: string;
}

export interface Menu_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  icon?: Icon;
  sub_menus: number[];
  parent_menu?: number;
  link: string;
}

export interface Menu_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  icon?: Icon;
  sub_menus: AdminPanelRelationPropertyModification<Menu_Plain>;
  parent_menu?: AdminPanelRelationPropertyModification<Menu_Plain>;
  link: string;
}
